parameters:
  project:
    name: Eureka
    target_root: .

  delivery:
    folder:
      parent: livraisons
      sources: src

    suffix_format: _`date +'%Y%m%d'`

environments:
  list:
    - prod
    - preprod
    - integ
    - recette

  prod:
    name: Production
    short: p
    suffix: __PROD__
    deploy:
      user: pi
      host: retropie
      proxy:
        user: test
        host: localhost

      target: /var/www
      commands:
        before_scripts:
          - ls -alh
          - pwd
          - date
        after_scripts :
          - ls -alh
          - date
      type: package

  preprod:
    short: pp
    name: Preproduction
    suffix: __PREPROD__
    deploy:
      user: smile
      host: localhost
      target: /var/www
      type: src

  integ:
    short: i
    name: Integration
    suffix: __INTEG__
    deploy:
      user: smile
      host: localhost
      target: /var/www
      type: sources

  recette:
    short: r
    name: Recette
    suffix: __RECETTE__
    deploy:
      user: recette
      host: localhost
      target: /var/www
      type: sources


